"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { CompetitionContextData } from "@/db/competition-context";
import type { ScoringMatch, ScoringWorkspaceData } from "@/db/scoring-engine";
import { useAdminActionDialog } from "../../admin-action-dialog";
import ScoringWorkspaceView, { scoringPhases, type ScoringDraft } from "./scoring-workspace-view";

const CACHE_TTL = 15_000;
const dataCache = new Map<string, { data: ScoringWorkspaceData; at: number }>();
const eventCache = new Map<string, { data: ScoringWorkspaceData; context: CompetitionContextData; at: number }>();
function makeDraft(match: ScoringMatch): ScoringDraft { return { scoreA: match.scoreA === null ? "" : String(match.scoreA), scoreB: match.scoreB === null ? "" : String(match.scoreB), resultType: match.resultType || "normal", note: "" }; }
function cacheKey(eventId: string, groupId: string, phase: string, date: string, showConfirmed: boolean) { return [eventId, groupId, phase, date, showConfirmed ? "all" : "todo"].join("|"); }
function replaceUrl(data: ScoringWorkspaceData) { const params = new URLSearchParams({ event: data.event.id }); if (data.filters.groupId) params.set("group", data.filters.groupId); if (data.filters.phaseCode) params.set("phase", data.filters.phaseCode); if (data.filters.date) params.set("date", data.filters.date); if (data.filters.showConfirmed) params.set("view", "all"); window.history.replaceState(window.history.state, "", `/admin/competition/scoring?${params.toString()}`); }
function clearEventCache(eventId: string) { for (const key of dataCache.keys()) if (key.startsWith(`${eventId}|`)) dataCache.delete(key); eventCache.delete(eventId); }
type Props = { initialEventId: string; initialData?: ScoringWorkspaceData | null; initialContext?: CompetitionContextData | null; initialGroupId?: string; initialPhase?: string; initialDate?: string; initialShowConfirmed?: boolean };

export default function ScoringLocalWorkspaceClient({ initialEventId, initialData = null, initialContext = null, initialGroupId = "", initialPhase = "qualifier-one", initialDate = "", initialShowConfirmed = false }: Props) {
  const [data, setData] = useState<ScoringWorkspaceData | null>(initialData); const [context, setContext] = useState<CompetitionContextData | null>(initialContext); const [drafts, setDrafts] = useState<Record<string, ScoringDraft>>(() => initialData ? Object.fromEntries(initialData.matches.map((match) => [match.assignmentId, makeDraft(match)])) : {}); const [query, setQuery] = useState(""); const [busyId, setBusyId] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(!initialData); const [loadError, setLoadError] = useState(""); const [selectedGroupId, setSelectedGroupId] = useState(initialData?.filters.groupId || initialGroupId); const [selectedPhase, setSelectedPhase] = useState(initialData?.filters.phaseCode || initialPhase); const [dirtyEvents, setDirtyEvents] = useState<Set<string>>(() => new Set()); const [eventId, setEventId] = useState(initialData?.event.id || initialEventId); const requestId = useRef(0); const { ask, dialog } = useAdminActionDialog();
  const applyData = useCallback((next: ScoringWorkspaceData) => { setData(next); setEventId(next.event.id); setSelectedGroupId(next.filters.groupId); setSelectedPhase(next.filters.phaseCode); setDrafts((current) => Object.fromEntries(next.matches.map((match) => [match.assignmentId, current[match.assignmentId] ?? makeDraft(match)]))); replaceUrl(next); }, []);
  useEffect(() => { if (!initialData || !initialContext) return; const key = cacheKey(initialData.event.id, initialData.filters.groupId, initialData.filters.phaseCode, initialData.filters.date, initialData.filters.showConfirmed); dataCache.set(key, { data: initialData, at: Date.now() }); eventCache.set(initialData.event.id, { data: initialData, context: initialContext, at: Date.now() }); }, [initialContext, initialData]);
  const fetchWorkspace = useCallback(async (input: { eventId: string; groupId?: string; phase?: string; date?: string; showConfirmed?: boolean; includeContext?: boolean; force?: boolean }) => {
    const currentData = data; const nextEventId = input.eventId; const groupId = input.groupId ?? currentData?.filters.groupId ?? initialGroupId; const phase = input.phase ?? currentData?.filters.phaseCode ?? initialPhase; const date = input.date ?? currentData?.filters.date ?? initialDate; const showConfirmed = input.showConfirmed ?? currentData?.filters.showConfirmed ?? initialShowConfirmed; const key = cacheKey(nextEventId, groupId, phase, date, showConfirmed); const currentRequest = ++requestId.current; const cached = !input.force ? dataCache.get(key) : undefined; setLoadError(""); setEventId(nextEventId);
    if (cached) { applyData(cached.data); if (Date.now() - cached.at < CACHE_TTL && !input.includeContext) { setLoading(false); return cached.data; } }
    setLoading(true);
    try { const params = new URLSearchParams({ eventId: nextEventId }); if (groupId) params.set("group", groupId); if (phase) params.set("phase", phase); if (date) params.set("date", date); if (showConfirmed) params.set("view", "all"); if (input.includeContext) params.set("context", "1"); const response = await fetch(`/api/admin/competition/scoring?${params.toString()}`, { cache: "no-store" }); const payload = await response.json() as { data?: ScoringWorkspaceData; context?: CompetitionContextData; error?: string }; if (!response.ok || !payload.data) throw new Error(payload.error || "比分数据读取失败。"); if (currentRequest !== requestId.current) return null; const nextKey = cacheKey(payload.data.event.id, payload.data.filters.groupId, payload.data.filters.phaseCode, payload.data.filters.date, payload.data.filters.showConfirmed); dataCache.set(nextKey, { data: payload.data, at: Date.now() }); if (payload.context) { setContext(payload.context); eventCache.set(nextEventId, { data: payload.data, context: payload.context, at: Date.now() }); } applyData(payload.data); return payload.data; }
    catch (failure) { if (currentRequest === requestId.current) setLoadError(failure instanceof Error ? failure.message : "比分数据读取失败。"); throw failure; }
    finally { if (currentRequest === requestId.current) setLoading(false); }
  }, [applyData, data, initialDate, initialGroupId, initialPhase, initialShowConfirmed]);
  useEffect(() => { if (!initialData && initialEventId) void fetchWorkspace({ eventId: initialEventId, groupId: initialGroupId, phase: initialPhase, date: initialDate, showConfirmed: initialShowConfirmed, includeContext: true, force: true }).catch(() => undefined); }, [fetchWorkspace, initialData, initialDate, initialEventId, initialGroupId, initialPhase, initialShowConfirmed]);
  useEffect(() => { const onSwitch = (event: Event) => { const detail = (event as CustomEvent<{ eventId?: string; previousEventId?: string; active?: string; competitionTool?: string }>).detail; if (detail?.active !== "competition" || detail.competitionTool !== "scoring" || !detail.eventId || detail.eventId === eventId) return; const nextEventId = detail.eventId; const previousEventId = detail.previousEventId || eventId; const cached = eventCache.get(nextEventId); if (cached && Date.now() - cached.at < CACHE_TTL) { setContext(cached.context); applyData(cached.data); setLoading(false); return; } void fetchWorkspace({ eventId: nextEventId, groupId: "", phase: "", date: "", showConfirmed: false, includeContext: true, force: true }).catch(() => { if (previousEventId) window.dispatchEvent(new CustomEvent("admin:event-switch-revert", { detail: { eventId: previousEventId } })); }); }; window.addEventListener("admin:event-switch", onSwitch); return () => window.removeEventListener("admin:event-switch", onSwitch); }, [applyData, eventId, fetchWorkspace]);
  const chooseGroup = (groupId: string) => { if (!data || groupId === selectedGroupId || loading) return; void fetchWorkspace({ eventId: data.event.id, groupId, phase: selectedPhase, date: "", showConfirmed: data.filters.showConfirmed }).catch(() => undefined); };
  const choosePhase = (phase: string) => { if (!data || phase === selectedPhase || loading) return; const stat = data.phases.find((item) => item.code === phase); if (!stat) { applyData({ ...data, filters: { ...data.filters, phaseCode: phase, date: "" }, dates: [], matches: [], counts: { actionable: 0, submitted: 0, confirmed: 0, visible: 0 } }); return; } void fetchWorkspace({ eventId: data.event.id, groupId: selectedGroupId, phase, date: "", showConfirmed: data.filters.showConfirmed }).catch(() => undefined); };
  const chooseDate = (date: string) => { if (data && date !== data.filters.date && !loading) void fetchWorkspace({ eventId: data.event.id, groupId: selectedGroupId, phase: selectedPhase, date, showConfirmed: data.filters.showConfirmed }).catch(() => undefined); };
  const toggleConfirmed = () => { if (data && !loading) void fetchWorkspace({ eventId: data.event.id, groupId: selectedGroupId, phase: selectedPhase, date: data.filters.date, showConfirmed: !data.filters.showConfirmed }).catch(() => undefined); };
  async function post(body: Record<string, unknown>, assignmentId: string) { if (!data) return false; setBusyId(assignmentId); setMessage(""); try { const response = await fetch("/api/admin/competition/scoring", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "操作失败。"); clearEventCache(data.event.id); setDirtyEvents((current) => new Set(current).add(data.event.id)); await fetchWorkspace({ eventId: data.event.id, groupId: selectedGroupId, phase: selectedPhase, date: data.filters.date, showConfirmed: data.filters.showConfirmed, force: true }); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败。"); return false; } finally { setBusyId(""); } }
  async function submit(match: ScoringMatch) { const draft = drafts[match.assignmentId] ?? makeDraft(match); const confirmed = await ask({ title: "提交这场赛果", description: `${match.playerAName || "A方"} ${draft.scoreA || "-"} : ${draft.scoreB || "-"} ${match.playerBName || "B方"}`, confirmLabel: "确认提交" }); if (!confirmed) return; const ok = await post({ action: "submit", assignmentId: match.assignmentId, ...draft }, match.assignmentId); if (ok) setMessage("赛果已保存并提交，等待组委会确认；尚未发布到用户端。"); }
  async function confirm(match: ScoringMatch) { const confirmed = await ask({ title: "确认赛果并推动晋级关系", description: "确认后该场会从默认待办列表消失；对用户端的显示仍需点击上方“发布到用户端”。", confirmLabel: "确认赛果" }); if (!confirmed) return; const ok = await post({ action: "confirm", assignmentId: match.assignmentId }, match.assignmentId); if (ok) setMessage("赛果已正式确认并推动后续签表。对阵与比分已进入“待发布”状态。"); }
  const statMap = new Map((data?.phases || []).map((phase) => [phase.code, phase]));
  const phaseOptions = scoringPhases.map((phase) => { const stat = statMap.get(phase.code); return { ...phase, hint: stat ? (stat.actionableCount ? `${stat.actionableCount}场待处理` : `${stat.confirmedCount}场已确认`) : loading ? "数据读取中" : "等待赛程" }; });
  const publicationDirty = data ? dirtyEvents.has(data.event.id) : false;
  return <div className={loading && data ? "admin-local-workspace is-refreshing" : "admin-local-workspace"}>{loading && data && <div className="admin-local-refresh"><i />正在更新比分工作区…</div>}{loadError && <div className="admin-local-error">{loadError}</div>}<ScoringWorkspaceView data={data} context={context} selectedGroupId={selectedGroupId || initialGroupId || "u16"} selectedPhase={selectedPhase || initialPhase || "qualifier-one"} phaseOptions={phaseOptions} drafts={drafts} query={query} busyId={busyId} message={message} loading={loading} publicationDirty={publicationDirty} onQueryChange={setQuery} onGroupChange={chooseGroup} onPhaseChange={choosePhase} onDateChange={chooseDate} onToggleConfirmed={toggleConfirmed} onDraftChange={(assignmentId, draft) => setDrafts((current) => ({ ...current, [assignmentId]: draft }))} onSubmit={submit} onConfirm={confirm} onPublicationChanged={context && data ? (status, dirty) => { setDirtyEvents((current) => { const next = new Set(current); if (!dirty) next.delete(data.event.id); else next.add(data.event.id); return next; }); setContext((current) => current ? ({ ...current, publications: { ...current.publications, matches: { ...current.publications.matches, status, hasUnpublishedChanges: dirty } } }) : current); } : undefined} />{dialog}</div>;
}
