"use client";

import { createPortal } from "react-dom";
import { useEffect, useMemo, useState } from "react";
import type { Group, Phase, PhaseId, Station } from "./public-types";
import type { PublicCompetitionEvent, PublicLiveMatch, PublicPhaseSummary } from "@/db/public-competition-live";

type LiveTab = "schedule" | "matches" | "rankings";
type StationMeta = Pick<Station, "id" | "eventId" | "title" | "city" | "phases" | "format" | "prizes">;

const PHASE_ORDER: PhaseId[] = ["qualifier-one", "qualifier-two", "main-one", "main-two"];
const PHASE_LABELS: Record<PhaseId, string> = {
  "qualifier-one": "资格赛第一场",
  "qualifier-two": "资格赛第二场",
  "main-one": "正赛第一阶段",
  "main-two": "正赛第二阶段",
};
const GROUP_LABELS: Record<string, string> = { "A":"第1组","B":"第2组","C":"第3组","D":"第4组","E":"第5组","F":"第6组","G":"第7组","H":"第8组" };

const liveCss = `
.public-competition-mode>.stack:not(.public-competition-overlay){display:none!important}
.public-competition-overlay{display:flex;flex-direction:column;gap:18px}
.public-live-stage-detail{display:flex;flex-direction:column;gap:14px}
.public-live-stage-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px 16px;border:1px solid #ebe6ef;border-radius:14px;background:#fff}
.public-live-stage-toolbar>div{min-width:0}.public-live-stage-toolbar small{color:#82639e;font-size:8px;font-weight:900}.public-live-stage-toolbar h2{margin:4px 0 3px;font-size:18px}.public-live-stage-toolbar p{margin:0;color:#8d8492;font-size:9px}
.public-live-stage-toolbar label{min-width:250px;display:flex;align-items:center;gap:8px;padding:9px 11px;border:1px solid #e3ddea;border-radius:10px;background:#faf9fb}.public-live-stage-toolbar input{width:100%;border:0;outline:0;background:transparent;font-size:10px}
.public-live-summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.public-live-summary article{padding:12px;border:1px solid #e7e1eb;border-radius:12px;background:#fff}.public-live-summary small{display:block;color:#918699;font-size:7px}.public-live-summary strong{display:block;margin-top:4px;font-size:18px}.public-live-summary span{color:#8c8191;font-size:8px}
.public-live-division{padding:14px;border:1px solid #e6e0e9;border-radius:14px;background:#fff}.public-live-division>header{display:flex;align-items:end;justify-content:space-between;gap:12px;margin-bottom:10px}.public-live-division h3{margin:4px 0 0;font-size:14px}.public-live-division header small{color:#8666a0;font-size:7px;font-weight:900}.public-live-division header span{color:#8b8191;font-size:8px}
.public-live-rounds{display:grid;grid-template-columns:repeat(5,minmax(180px,1fr));gap:8px;overflow-x:auto;padding-bottom:4px}.public-live-round{min-width:180px}.public-live-round>h4{margin:0 0 7px;padding:7px 8px;border-radius:8px;color:#684290;background:#f4eff9;font-size:9px}.public-live-round-list{display:flex;flex-direction:column;gap:6px}
.public-live-round-list .stage-tree-match,.public-main-match{position:relative!important;left:auto!important;top:auto!important;width:auto!important;min-height:0!important;padding:7px 8px!important;border:1px solid #e9e3ed!important;border-radius:9px!important;background:#fbfafc!important;box-shadow:none!important}.public-live-round-list .stage-tree-match.match-hit,.public-main-match.match-hit{outline:2px solid #9b65d5;background:#f4edfb!important}
.public-live-round-list .stage-competitor,.public-main-match .stage-competitor{display:grid!important;grid-template-columns:28px minmax(0,1fr) 26px!important;align-items:center!important;gap:4px!important;min-height:21px!important;border:0!important;padding:0!important}.public-live-round-list .stage-slot,.public-main-match .stage-slot{color:#987da9;font-size:7px}.public-live-round-list .stage-competitor span:not(.stage-slot),.public-main-match .stage-competitor span:not(.stage-slot){overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#32293a;font-size:9px;font-weight:700}.public-live-round-list .stage-competitor b,.public-main-match .stage-competitor b{justify-self:end;color:#5f358d;font-size:10px}.public-live-round-list .stage-between,.public-main-match .stage-between{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:5px!important;margin:3px 0!important;color:#938799!important;font-size:7px!important}.public-live-round-list .stage-between span.tv,.public-main-match .stage-between span.tv{color:#d03e89;font-weight:900}.public-live-round-list .stage-game-no,.public-main-match .stage-game-no{display:block!important;margin-top:4px;color:#a093a8;font-size:6px!important;font-weight:700!important;text-align:right}
.public-live-prelim{padding:14px;border:1px solid #e6e0e9;border-radius:14px;background:#fff}.public-live-prelim-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}
.public-main-board{display:flex;flex-direction:column;gap:14px}.public-main-group{padding:15px;border:1px solid #e5dfeb;border-radius:15px;background:#fff}.public-main-group>header{display:flex;align-items:end;justify-content:space-between;margin-bottom:10px}.public-main-group>header h3{margin:4px 0 0;font-size:14px}.public-main-group>header small{color:#82629f;font-size:7px;font-weight:900}.public-main-group>header span{font-size:8px;color:#8a8091}.public-main-group-grid{display:grid;grid-template-columns:1.25fr .8fr .8fr;gap:10px}.public-main-lane{padding:10px;border-radius:11px;background:#f8f6fa}.public-main-lane.winner{background:#f4f8ff}.public-main-lane.loser{background:#fff6fa}.public-main-lane h4{margin:0 0 7px;font-size:9px;color:#69418c}.public-main-lane>div{display:flex;flex-direction:column;gap:6px}
.public-main-pending{padding:24px;border:1px dashed #d9cfe4;border-radius:16px;background:#fff;text-align:center}.public-main-pending span{display:inline-flex;padding:6px 9px;border-radius:999px;color:#74479b;background:#efe8f7;font-size:8px;font-weight:900}.public-main-pending h2{margin:10px 0 6px;font-size:20px}.public-main-pending p{max-width:680px;margin:0 auto;color:#84798a;font-size:10px;line-height:1.8}
.public-live-roster-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-bottom:12px}.public-live-roster-summary article{padding:14px;border:1px solid #e8e2ec;border-radius:12px;background:#fff}.public-live-roster-summary small{display:block;color:#918696;font-size:7px}.public-live-roster-summary strong{display:block;margin-top:5px;font-size:21px}.public-live-roster-summary span{color:#867b8d;font-size:8px}.public-roster-groups{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.public-roster-group{padding:13px;border:1px solid #e8e2ec;border-radius:12px;background:#fff}.public-roster-group header{display:flex;justify-content:space-between;align-items:end;margin-bottom:9px}.public-roster-group h3{margin:3px 0 0;font-size:12px}.public-roster-group header span{color:#774f98;font-size:8px;font-weight:900}.public-roster-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.public-roster-grid div{display:flex;align-items:center;gap:6px;min-width:0;padding:7px 8px;border-radius:8px;background:#f8f6fa}.public-roster-grid span{width:22px;color:#9b8ba5;font-size:7px}.public-roster-grid strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9px}
.public-live-ranking-note{margin-bottom:12px;padding:13px 14px;border-radius:12px;color:#5f3d83;background:#f1eafa;font-size:9px;line-height:1.7}.public-live-day-status{display:inline-flex;padding:5px 8px;border-radius:999px;color:#287350;background:#e9f8f0;font-size:7px;font-weight:900}
.public-live-main-ready{padding:18px;border:1px solid #e4ddea;border-radius:15px;background:linear-gradient(145deg,#fff,#f6f0fb)}.public-live-main-ready h2{margin:5px 0 7px;font-size:19px}.public-live-main-ready p{margin:0;color:#817488;font-size:9px;line-height:1.7}.public-live-main-ready strong{color:#633891}
.tabs.public-five-tabs{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;width:min(620px,100%)!important}.tabs.public-five-tabs button{min-width:0}
@media(max-width:1100px){.public-live-summary{grid-template-columns:repeat(3,minmax(0,1fr))}.public-live-prelim-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.public-roster-groups{grid-template-columns:1fr 1fr}.public-main-group-grid{grid-template-columns:1fr 1fr}.public-main-group-grid>.public-main-lane:first-child{grid-column:1/-1}}
@media(max-width:760px){.public-live-stage-toolbar{align-items:stretch;flex-direction:column}.public-live-stage-toolbar label{min-width:0}.public-live-summary{grid-template-columns:1fr 1fr}.public-live-prelim-grid{grid-template-columns:1fr}.public-roster-groups{grid-template-columns:1fr}.public-live-roster-summary{grid-template-columns:1fr 1fr}.public-live-rounds{grid-template-columns:repeat(5,190px)}.public-main-group-grid{grid-template-columns:1fr}.public-main-group-grid>.public-main-lane:first-child{grid-column:auto}.tabs.public-five-tabs{width:100%!important}.tabs.public-five-tabs button{font-size:10px!important;padding:8px 2px!important}}
`;

function GroupSwitch({ group, setGroup }: { group: Group; setGroup: (group: Group) => void }) {
  return <div className="group-switch" aria-label="选择比赛组别"><button className={group === "少年组" ? "active" : ""} onClick={() => setGroup("少年组")}><b>U16</b><span>少年组</span></button><button className={group === "青年组" ? "active" : ""} onClick={() => setGroup("青年组")}><b>U20</b><span>青年组</span></button></div>;
}
function shortDate(value: string | null) { if (!value) return "时间待定"; const [,m,d]=value.split("-"); return m&&d?`${Number(m)}月${Number(d)}日`:value; }
function compactDate(value: string) { const [,m,d]=value.split("-"); return m&&d?`${m}-${d}`:value; }
function weekday(value: string) { const labels=["周日","周一","周二","周三","周四","周五","周六"]; const date=new Date(`${value}T12:00:00+08:00`); return Number.isNaN(date.getTime())?"":labels[date.getDay()]; }
function scoreLabel(match: PublicLiveMatch) { if(match.status==="auto_advanced")return "轮空"; if(match.scoreA==null||match.scoreB==null)return "— : —"; return `${match.scoreA} : ${match.scoreB}`; }
function matchStatus(match: PublicLiveMatch) { if(match.status==="auto_advanced")return "自动晋级"; if(match.resultStatus==="confirmed")return "已结束"; if(match.resultStatus==="submitted")return "待确认"; return "待开始"; }
function phaseFor(station: StationMeta,id:PhaseId):Phase { return station.phases.find(item=>item.id===id)??{id,number:String(PHASE_ORDER.indexOf(id)+1).padStart(2,"0"),title:PHASE_LABELS[id],date:"待公布",status:"待开始"}; }
function phaseSummary(data:PublicCompetitionEvent,group:Group,phaseId:PhaseId){return data.phaseSummaries.find(item=>item.group===group&&item.phaseId===phaseId);}
function phaseMatches(data:PublicCompetitionEvent,group:Group,phaseId:PhaseId){return data.matches.filter(item=>item.group===group&&item.phaseId===phaseId);}
function raceLabel(group:Group,phase:PhaseId){if(phase.startsWith("qualifier"))return group==="少年组"?"9局5胜":"13局7胜";if(phase==="main-one")return group==="少年组"?"13局7胜":"17局9胜";return group==="少年组"?"17局9胜":"21局11胜";}

function StageMatchCard({match,query=""}:{match:PublicLiveMatch;query?:string}){
  const q=query.trim().toLowerCase(); const hit=Boolean(q)&&[match.playerA,match.playerB,match.table,match.matchCode].some(v=>(v??"").toLowerCase().includes(q)); const showSlots=match.roundNo===1;
  return <article className={`stage-tree-match public-main-match${hit?" match-hit":""}`} data-public-live-hit={hit?"true":undefined}><div className="stage-competitor"><span className="stage-slot">{showSlots&&match.sourceAType==="slot"?String(match.sourceARef??"").padStart(2,"0"):""}</span><span>{match.playerA||"待定"}</span><b>{match.status==="auto_advanced"?"✓":match.scoreA??"—"}</b></div><div className="stage-between"><time>{match.date?`${shortDate(match.date)} ${match.time??""}`:match.status==="auto_advanced"?"自动晋级":"时间待定"}</time><span className={match.isTv?"tv":""}>{match.table||(match.status==="auto_advanced"?"轮空":"球台待定")}</span></div><div className="stage-competitor"><span className="stage-slot">{showSlots&&match.sourceBType==="slot"?String(match.sourceBRef??"").padStart(2,"0"):""}</span><span>{match.playerB||(match.status==="auto_advanced"?"轮空":"待定")}</span><b>{match.status==="auto_advanced"?"—":match.scoreB??"—"}</b></div><b className="stage-game-no">{match.matchCode}</b></article>;
}

function QualifierStageDetail({station,data,group,setGroup,phaseId,onBack}:{station:StationMeta;data:PublicCompetitionEvent;group:Group;setGroup:(g:Group)=>void;phaseId:PhaseId;onBack:()=>void}){
  const [query,setQuery]=useState(""); const summary=phaseSummary(data,group,phaseId); const matches=phaseMatches(data,group,phaseId); const prelim=matches.filter(item=>item.roundNo===0); const divisions=summary?.divisionCount??16;
  useEffect(()=>{if(!query.trim())return;const timer=window.setTimeout(()=>document.querySelector<HTMLElement>('[data-public-live-hit="true"]')?.scrollIntoView({behavior:"smooth",block:"center"}),80);return()=>window.clearTimeout(timer);},[query,group,phaseId]);
  if(!summary)return <PendingStage station={station} group={group} setGroup={setGroup} phaseId={phaseId} onBack={onBack} text="该阶段已经开放，但组委会尚未发布完整签表。"/>;
  return <div className="bracket-page stack public-live-stage-detail"><button className="draw-back" onClick={onBack}>‹ 返回赛程阶段</button><section className="bracket-title with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>{PHASE_LABELS[phaseId]}</h1><p>16个分区连续展示；第一轮显示签位，姓名右侧显示比分，中间显示时间和台号。</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="public-live-stage-toolbar"><div><small>{group} · 详细赛程表</small><h2>{PHASE_LABELS[phaseId]}</h2><p>{summary.entrantCount}人 · {summary.divisionCount}区 · 每区{summary.divisionSize}人 · {raceLabel(group,phaseId)}</p></div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索球员、球台或场次"/></label></section><section className="public-live-summary"><article><small>实际参赛</small><strong>{summary.entrantCount}</strong><span>人</span></article><article><small>附加赛</small><strong>{summary.playoffMatchCount}</strong><span>场</span></article><article><small>轮空</small><strong>{summary.byeCount}</strong><span>个</span></article><article><small>分区</small><strong>{summary.divisionCount}</strong><span>{summary.divisionSize}人/区</span></article><article><small>晋级</small><strong>{summary.totalQualifierCount}</strong><span>人</span></article></section>{prelim.length>0&&<section className="public-live-prelim"><header><small>附加赛</small><h3>{prelim.length}场 · 胜者进入512签表</h3></header><div className="public-live-prelim-grid">{prelim.map(m=><StageMatchCard key={m.id} match={m} query={query}/>)}</div></section>}{Array.from({length:divisions},(_,index)=>index+1).map(no=>{const region=matches.filter(m=>m.divisionNo===no&&m.roundNo>0);return <section className="public-live-division" key={no}><header><div><small>第{no}区</small><h3>32人完整签表</h3></div><span>分区冠军直接晋级</span></header><div className="public-live-rounds">{[1,2,3,4,5].map(round=><div className="public-live-round" key={round}><h4>{region.find(m=>m.roundNo===round)?.roundName||["32进16","16进8","8进4","4进2","分区决胜"][round-1]}</h4><div className="public-live-round-list">{region.filter(m=>m.roundNo===round).map(m=><StageMatchCard key={m.id} match={m} query={query}/>)}</div></div>)}</div></section>})}</div>;
}

function PendingStage({station,group,setGroup,phaseId,onBack,text}:{station:StationMeta;group:Group;setGroup:(g:Group)=>void;phaseId:PhaseId;onBack:()=>void;text:string}){
  return <div className="bracket-page stack public-live-stage-detail"><button className="draw-back" onClick={onBack}>‹ 返回赛程阶段</button><section className="bracket-title with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>{PHASE_LABELS[phaseId]}</h1><p>页面已开放，未发布的数据会保留明确说明。</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="public-main-pending"><span>赛程状态</span><h2>签表待公布</h2><p>{text}</p></section></div>;
}

function MainOneDetail({station,data,group,setGroup,onBack}:{station:StationMeta;data:PublicCompetitionEvent;group:Group;setGroup:(g:Group)=>void;onBack:()=>void}){
  const [query,setQuery]=useState(""); const matches=phaseMatches(data,group,"main-one"); const summary=phaseSummary(data,group,"main-one");
  if(!summary||!matches.length)return <PendingStage station={station} group={group} setGroup={setGroup} phaseId="main-one" onBack={onBack} text="64人正赛名单已经产生，但正式双败抽签尚未发布。抽签发布后，这里会按8组双败结构显示。"/>;
  return <div className="bracket-page stack public-live-stage-detail"><button className="draw-back" onClick={onBack}>‹ 返回赛程阶段</button><section className="bracket-title with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>正赛第一阶段</h1><p>64人分8组双败；每组胜部2人、败部2人，共32人晋级。</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="public-live-stage-toolbar"><div><small>{group} · 双败签表</small><h2>8组双败 · 64进32</h2><p>中间首轮对阵，胜部和败部独立流转；{raceLabel(group,"main-one")}</p></div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索球员、球台或场次"/></label></section><div className="public-main-board">{Array.from({length:8},(_,index)=>index+1).map(no=>{const rows=matches.filter(m=>m.divisionNo===no);const first=rows.filter(m=>m.roundName==="小组第一轮");const winner=rows.filter(m=>m.roundName==="胜部晋级轮");const loser=[...rows.filter(m=>m.roundName==="败部第一轮"),...rows.filter(m=>m.roundName==="败部晋级轮")];const letter=String.fromCharCode(64+no);return <section className="public-main-group" key={no}><header><div><small>{letter}组 · 双败</small><h3>{GROUP_LABELS[letter]}</h3></div><span>8人 → 4人晋级</span></header><div className="public-main-group-grid"><div className="public-main-lane"><h4>首轮对阵</h4><div>{first.map(m=><StageMatchCard key={m.id} match={m} query={query}/>)}</div></div><div className="public-main-lane winner"><h4>胜部 · 2人晋级</h4><div>{winner.map(m=><StageMatchCard key={m.id} match={m} query={query}/>)}</div></div><div className="public-main-lane loser"><h4>败部 · 2人晋级</h4><div>{loser.map(m=><StageMatchCard key={m.id} match={m} query={query}/>)}</div></div></div></section>})}</div></div>;
}

function MainTwoDetail({station,data,group,setGroup,onBack}:{station:StationMeta;data:PublicCompetitionEvent;group:Group;setGroup:(g:Group)=>void;onBack:()=>void}){
  const [query,setQuery]=useState(""); const matches=phaseMatches(data,group,"main-two"); const summary=phaseSummary(data,group,"main-two");
  if(!summary||!matches.length)return <PendingStage station={station} group={group} setGroup={setGroup} phaseId="main-two" onBack={onBack} text="正赛第二阶段功能已经开放。需要等待正赛第一阶段产生32名晋级球员后重新抽签：16名胜部晋级进入种子位，16名败部晋级混抽。"/>;
  const bracket=matches.filter(m=>m.matchCode!=="M2-3RD"); const third=matches.find(m=>m.matchCode==="M2-3RD");
  return <div className="bracket-page stack public-live-stage-detail"><button className="draw-back" onClick={onBack}>‹ 返回赛程阶段</button><section className="bracket-title with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>正赛第二阶段</h1><p>32强重新抽签，单败淘汰至冠军；三、四名决赛独立显示。</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="public-live-stage-toolbar"><div><small>{group} · 32强签表</small><h2>32强至冠军</h2><p>16名胜部晋级球员进入种子位，败部晋级球员混抽；{raceLabel(group,"main-two")}</p></div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索球员、球台或场次"/></label></section><section className="public-live-division"><div className="public-live-rounds">{[1,2,3,4,5].map(round=><div className="public-live-round" key={round}><h4>{["32进16","16进8","8进4","半决赛","决赛"][round-1]}</h4><div className="public-live-round-list">{bracket.filter(m=>m.roundNo===round).map(m=><StageMatchCard key={m.id} match={m} query={query}/>)}</div></div>)}</div>{third&&<div style={{marginTop:10,maxWidth:260}}><h4 style={{fontSize:10}}>三、四名决赛</h4><StageMatchCard match={third} query={query}/></div>}</section></div>;
}

function MainRosterDetail({station,data,group,setGroup,onBack}:{station:StationMeta;data:PublicCompetitionEvent;group:Group;setGroup:(g:Group)=>void;onBack:()=>void}){
  const roster=data.mainRoster.filter(item=>item.group===group).sort((a,b)=>a.sortOrder-b.sortOrder);const q1=roster.filter(i=>i.sourceType==="qualifier_one_qualified");const q2=roster.filter(i=>i.sourceType==="qualifier_two_qualified");const seeds=roster.filter(i=>i.sourceType==="seed");
  return <div className="bracket-page stack public-live-stage-detail"><button className="draw-back" onClick={onBack}>‹ 返回</button><section className="bracket-title with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>正赛64人名单</h1><p>资格赛48人 + 种子16人</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="public-live-main-ready"><small>MAIN DRAW · 64</small><h2><strong>{roster.length}/64</strong> 正赛名单已就绪</h2><p>名单与正赛抽签独立保存；正赛抽签发布后，在“赛程”中查看8组双败签表。</p></section><section className="public-roster-groups">{[["资格赛第一场晋级",q1],["资格赛第二场晋级",q2],["种子选手",seeds]].map(([title,values])=><article className="public-roster-group" key={String(title)}><header><div><small>MAIN ROSTER</small><h3>{String(title)}</h3></div><span>{(values as typeof roster).length}人</span></header><div className="public-roster-grid">{(values as typeof roster).map((p,i)=><div key={p.playerId}><span>{String(i+1).padStart(2,"0")}</span><strong>{p.playerName}</strong></div>)}</div></article>)}</section></div>;
}

function PublicSchedule({station,data}:{station:StationMeta;data:PublicCompetitionEvent}){
  const [group,setGroup]=useState<Group>("少年组"); const [detail,setDetail]=useState<PhaseId|null>(null);
  if(detail?.startsWith("qualifier"))return <QualifierStageDetail station={station} data={data} group={group} setGroup={setGroup} phaseId={detail} onBack={()=>setDetail(null)}/>;
  if(detail==="main-one")return <MainOneDetail station={station} data={data} group={group} setGroup={setGroup} onBack={()=>setDetail(null)}/>;
  if(detail==="main-two")return <MainTwoDetail station={station} data={data} group={group} setGroup={setGroup} onBack={()=>setDetail(null)}/>;
  return <div className="schedule-page stack public-competition-overlay"><section className="schedule-head with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>赛程</h1><p>按比赛阶段查看完整赛程表</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="phase-schedule compact-phases">{PHASE_ORDER.map(phaseId=>{const phase=phaseFor(station,phaseId);const summary=phaseSummary(data,group,phaseId);const phaseMs=phaseMatches(data,group,phaseId);const rosterCount=phaseId==="main-one"?data.mainRoster.filter(i=>i.group===group).length:0;const qualifier=phaseId.startsWith("qualifier");const progress=qualifier&&summary?`${summary.entrantCount}人 → 晋级24人`:phaseId==="main-one"?`64进32 · ${summary?"正式签表已发布":`正赛名单 ${rosterCount}/64`}`:summary?"32进1 · 正式签表已发布":"32进1 · 等待重新抽签";const note=qualifier&&summary?`${summary.playoffMatchCount?`附加赛${summary.playoffMatchCount}场 · `:""}${summary.byeCount?`轮空${summary.byeCount}个 · `:""}${summary.divisionCount}个分区`:phaseId==="main-one"?(phaseMs.length?"8组双败签表和比赛时间已发布":"64人名单已就绪，等待正赛抽签"):summary?"32强单败至冠军":"正赛第一阶段结束并确认32强后发布";return <article className="phase-card compact-phase" key={phaseId}><div className="phase-status-line"><b className={`phase-status status-${phase.status}`}>{phase.status}</b><time>{phase.date}</time></div><h2>{phase.title}</h2><h3>{progress}</h3><div className="phase-meta"><span>{qualifier?"一次抽签到底 · 16区":phaseId==="main-one"?"8组双败":"32强单败"}</span><span>{raceLabel(group,phaseId)}</span></div>{qualifier&&<div className="qualify-rule"><strong>晋级24人</strong><span>16名分区冠军直接晋级</span><i>＋</i><span>决胜负者按局胜率取前8</span></div>}<footer><small>{note}</small><button onClick={()=>setDetail(phaseId)}>{summary||phaseMs.length?"查看赛程表":"查看阶段说明"} <i>›</i></button></footer></article>})}</section></div>;
}

function PublicMatches({station,data}:{station:StationMeta;data:PublicCompetitionEvent}){
  const [group,setGroup]=useState<Group>("少年组");const all=useMemo(()=>data.matches.filter(m=>m.group===group&&m.date),[data.matches,group]);const days=useMemo(()=>[...new Set(all.map(m=>m.date!).filter(Boolean))].sort(),[all]);const today="2026-08-07";const defaultDay=[...days].filter(d=>d<=today).at(-1)??days[0]??"";const [day,setDay]=useState(defaultDay);const selectedDay=days.includes(day)?day:defaultDay;const [query,setQuery]=useState("");const matches=all.filter(m=>m.date===selectedDay&&[m.playerA,m.playerB,m.table,m.roundName,m.matchCode].some(v=>(v??"").includes(query.trim())));
  return <div className="match-list-page stack public-competition-overlay"><section className="match-list-head with-group compact-head"><div><small className="event-name-kicker">{station.title}</small><h1>对阵</h1><p>按日期查看比赛对阵、比分和球台</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="match-filter"><nav className="match-days">{days.map(value=><button className={selectedDay===value?"active":""} onClick={()=>setDay(value)} key={value}><small>{weekday(value)}</small><b>{compactDate(value)}</b></button>)}</nav><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索球员、球台或场次"/></label></section><div className="match-count"><strong>{selectedDay?compactDate(selectedDay):"—"}</strong><span>{group} · {matches.length}场对阵</span></div>{matches.length?<section className="versus-list">{matches.map(match=><article className="versus-card" key={match.id}><header><b>{match.time||"待定"}</b><span>{PHASE_LABELS[match.phaseId]} · {match.roundName} · {match.matchCode}</span></header><section><div className="match-player"><i>{(match.playerA||"待").slice(0,1)}</i><strong>{match.playerA||"待定"}</strong></div><div className="match-center"><strong>{scoreLabel(match)}</strong><span className={matchStatus(match)==="已结束"?"ended":""}>{matchStatus(match)}</span><b className={match.isTv?"tv":""}>{match.table||"球台待定"}</b></div><div className="match-player"><i>{(match.playerB||"待").slice(0,1)}</i><strong>{match.playerB||"待定"}</strong></div></section></article>)}</section>:<section className="match-empty"><i>○</i><h2>当日对阵待公布</h2><p>该日期目前没有已发布的比赛；可切换其它日期查看。</p></section>}</div>;
}

function PublicRankings({station,data}:{station:StationMeta;data:PublicCompetitionEvent}){
  const [group,setGroup]=useState<Group>("少年组");const roster=data.mainRoster.filter(i=>i.group===group).sort((a,b)=>a.sortOrder-b.sortOrder);const q1=data.qualificationEntries.filter(i=>i.group===group&&i.phaseId==="qualifier-one"&&(i.entryType==="direct"||i.selected));const q2=data.qualificationEntries.filter(i=>i.group===group&&i.phaseId==="qualifier-two"&&(i.entryType==="direct"||i.selected));const seeds=roster.filter(i=>i.sourceType==="seed");const mainOne=phaseMatches(data,group,"main-one");const mainTwo=phaseMatches(data,group,"main-two");
  return <div className="stack public-competition-overlay"><section className="ranking-head"><div><small className="event-name-kicker">{station.title}</small><h1>比赛排名</h1><p>赛事进行中，先展示已确认晋级与正赛名单。</p></div><GroupSwitch group={group} setGroup={setGroup}/></section><section className="card ranking"><div className="public-live-ranking-note"><strong>当前赛事尚未产生最终名次。</strong><br/>资格赛已经结束；正赛第一阶段{mainOne.length?"签表已发布，将于8月8日开始":"等待抽签"}。正赛第二阶段{mainTwo.length?"签表已发布":"将在32强确认后重新抽签"}。</div><div className="public-live-roster-summary"><article><small>资格赛第一场</small><strong>{q1.length}</strong><span>人晋级</span></article><article><small>资格赛第二场</small><strong>{q2.length}</strong><span>人晋级</span></article><article><small>种子</small><strong>{seeds.length}</strong><span>人</span></article><article><small>正赛名单</small><strong>{roster.length}/64</strong><span>已确认</span></article></div><button className="more" onClick={()=>{}}>正赛64人名单已确认</button></section></div>;
}

function CompetitionOverlay({tab,station,data}:{tab:LiveTab;station:StationMeta;data:PublicCompetitionEvent}){if(tab==="schedule")return <PublicSchedule station={station} data={data}/>;if(tab==="matches")return <PublicMatches station={station} data={data}/>;return <PublicRankings station={station} data={data}/>;}

export default function PublicCompetitionLiveEnhancer({stations,events}:{stations:StationMeta[];events:PublicCompetitionEvent[]}){
  const [activeTab,setActiveTab]=useState<LiveTab|null>(null);const [currentStationId,setCurrentStationId]=useState("");const [target,setTarget]=useState<HTMLElement|null>(null);const stationById=useMemo(()=>new Map(stations.map(s=>[s.id,s])),[stations]);const competitionByEvent=useMemo(()=>new Map(events.map(e=>[e.eventId,e])),[events]);const station=stationById.get(currentStationId);const competition=station?competitionByEvent.get(station.eventId):undefined;
  useEffect(()=>{if(!document.getElementById("public-live-competition-css")){const style=document.createElement("style");style.id="public-live-competition-css";style.textContent=liveCss;document.head.append(style);}const detect=()=>{const hero=document.querySelector<HTMLElement>(".station-hero");let next="";if(hero){const cls=[...hero.classList].find(name=>name.startsWith("station-")&&name!=="station-hero");if(cls)next=cls.slice(8);}if(next!==currentStationId){setCurrentStationId(next);setActiveTab(null);}const meta=stationById.get(next);const live=meta?competitionByEvent.get(meta.eventId):undefined;const tabs=document.querySelector<HTMLElement>(".tabs");const content=document.querySelector<HTMLElement>(".content");setTarget(cur=>cur===content?cur:content);document.querySelectorAll<HTMLElement>("[data-public-comp-tab],[data-public-comp-action]").forEach(el=>{if(!live&&el.isConnected)el.remove();});if(!live||!tabs)return;tabs.classList.remove("short-tabs");tabs.classList.add("public-five-tabs");([['schedule','赛程'],['matches','对阵'],['rankings','排名']] as Array<[LiveTab,string]>).forEach(([id,label])=>{if(tabs.querySelector(`[data-public-comp-tab="${id}"]`))return;const b=document.createElement("button");b.type="button";b.dataset.publicCompTab=id;b.textContent=label;tabs.appendChild(b);});const heroButtons=document.querySelector<HTMLElement>(".station-hero .hero-buttons");if(heroButtons&&!heroButtons.querySelector('[data-public-comp-action="schedule"]')){const b=document.createElement("button");b.type="button";b.dataset.publicCompAction="schedule";b.textContent="查看赛程";heroButtons.prepend(b);}const intro=document.querySelector<HTMLElement>(".introduction .inline-actions");if(intro&&!intro.querySelector('[data-public-comp-action="schedule"]')){const b=document.createElement("button");b.type="button";b.dataset.publicCompAction="schedule";b.textContent="查看分阶段赛程";intro.appendChild(b);}};const click=(event:MouseEvent)=>{const el=event.target as Element|null;const liveButton=el?.closest<HTMLElement>("[data-public-comp-tab],[data-public-comp-action]");if(liveButton){const id=(liveButton.dataset.publicCompTab||liveButton.dataset.publicCompAction) as LiveTab;if(id){event.preventDefault();event.stopPropagation();setActiveTab(id);window.scrollTo({top:0,behavior:"smooth"});}return;}const normal=el?.closest<HTMLElement>(".tabs button");if(normal&&!normal.dataset.publicCompTab)setActiveTab(null);};document.addEventListener("click",click,true);const observer=new MutationObserver(detect);observer.observe(document.body,{childList:true,subtree:true});detect();const timer=window.setInterval(detect,300);return()=>{document.removeEventListener("click",click,true);observer.disconnect();window.clearInterval(timer);};},[competitionByEvent,currentStationId,stationById]);
  useEffect(()=>{const content=document.querySelector<HTMLElement>(".content");if(!content)return;content.classList.toggle("public-competition-mode",Boolean(activeTab&&competition));const tabs=content.querySelector<HTMLElement>(".tabs");if(activeTab&&tabs)tabs.querySelectorAll("button").forEach(button=>button.classList.toggle("active",(button as HTMLElement).dataset.publicCompTab===activeTab));},[activeTab,competition]);
  if(!target||!station||!competition||!activeTab)return null;return createPortal(<CompetitionOverlay tab={activeTab} station={station} data={competition}/>,target);
}
